# Generated by Django 3.1.5 on 2021-02-15 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_auto_20210209_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GST', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.clients')),
            ],
        ),
    ]
